replicaCount: 1

image:
  repository: prom/prometheus
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9090

app:
  targetPort: 9090

resources: 
  limits:
    memory: "512Mi"
    cpu: "500m"