image:
  repository: prom/node-exporter
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9100

app:
  targetPort: 9100

resources: 
  limits:
    memory: "128Mi"
    cpu: "500m"
