apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "prometheus.fullname" . }}-config"
data:
  prometheus.yml: |-
{{ .Files.Get "app-data/prometheus.yml" | indent 4 }}
  rules.yml: |-
{{ .Files.Get "app-data/rules.yml" | indent 4 }}
