apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "prometheus.fullname" . }}
  labels:
{{ include "prometheus.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-targer: /
spec:
  rules:
    - http:
        paths:
          - path: /prometheus
            backend:
              serviceName: prometheus
              servicePort: http
