apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-test-python.fullname" . }}
  labels:
{{ include "prometheus-test-python.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape }}
    prometheus.io/path: {{ .Values.prometheus.path }}
    prometheus.io/port: {{ .Values.prometheus.port }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http 
      port: {{ .Values.service.appPort }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics 
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "prometheus-test-python.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
