replicaCount: 1

image:
  repository: prom/alertmanager
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9093

app:
  targetPort: 9093

resources:
  limits:
    memory: "128Mi"
    cpu: "500m"
