apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
{{ include "backend.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: {{ .Values.prometheus.scrape }}
    prometheus.io/path: {{ .Values.prometheus.path }}
    prometheus.io/port: {{ .Values.prometheus.port }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "backend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
